language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"


# install deps
install:
    - pip install flake8 isort coverage coveralls
    - pip install -r requirements.txt

before_script:
   - flake8 --show-source .
   - isort -rc .

# run tests
script: coverage run --source=pyfirmata tests.py

after_success:
    - coveralls
